// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi6ztThJPVulr2zD6fMQB-pOdzQFHY33k',
    appId: '1:155428993295:web:7a0f24cbc9e496d714267a',
    messagingSenderId: '155428993295',
    projectId: 'wallert-app',
    authDomain: 'wallert-app.firebaseapp.com',
    storageBucket: 'wallert-app.firebasestorage.app',
    measurementId: 'G-5Q6LH2PRG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ7GIDGasoSsO4GGtVXem2pAYVTBftUSc',
    appId: '1:155428993295:android:c60b30992138a2a214267a',
    messagingSenderId: '155428993295',
    projectId: 'wallert-app',
    storageBucket: 'wallert-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKf_bYpkUJqKKaaUF5tS_jKkoyDqOOL0E',
    appId: '1:155428993295:ios:d3f62edbbc10ef5c14267a',
    messagingSenderId: '155428993295',
    projectId: 'wallert-app',
    storageBucket: 'wallert-app.firebasestorage.app',
    iosBundleId: 'com.example.wallertApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKf_bYpkUJqKKaaUF5tS_jKkoyDqOOL0E',
    appId: '1:155428993295:ios:d3f62edbbc10ef5c14267a',
    messagingSenderId: '155428993295',
    projectId: 'wallert-app',
    storageBucket: 'wallert-app.firebasestorage.app',
    iosBundleId: 'com.example.wallertApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi6ztThJPVulr2zD6fMQB-pOdzQFHY33k',
    appId: '1:155428993295:web:0f2291febf69656c14267a',
    messagingSenderId: '155428993295',
    projectId: 'wallert-app',
    authDomain: 'wallert-app.firebaseapp.com',
    storageBucket: 'wallert-app.firebasestorage.app',
    measurementId: 'G-N28E5ZKQBC',
  );

}